services:
  mysql:
    image: mysql:9.4.0
    container_name: movie-reservation-mysql
    environment:
      MYSQL_DATABASE: movie_reservation
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      timeout: 20s
      retries: 10

volumes:
  mysql-data: